settings:
  title: 'Status'
  url: 'https://status.aly.pet' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: aly-pet
    name: aly.pet
    description: 'Public website'
    url: 'https://aly.pet/'

  - id: home-aly-pet
    name: home.aly.pet
    description: 'Home frontend'
    url: 'https://home.aly.pet'

  - id: photos-aly-pet
    name: photos.aly.pet
    description: 'Photos hosting'
    url: 'https://photos.aly.pet/'

  - id: gist-aly-pet
    name: gist.aly.pet
    description: 'Gist clone'
    url: 'https://gist.aly.pet/'

  - id: s3-aly-pet
    name: s3.aly.pet
    description: 'Storage'
    url: 'https://s3.aly.pet/'
